#pragma once

#include "types.hpp"
#include "constants.hpp"

using namespace arma;

class Model
{
public:
	typedef arma::vec::fixed<states::state_size> state_type;
	typedef state_type deriv_type;

	typedef arma::vec::fixed<outputs::output_size> observer_type;
	typedef arma::vec::fixed<inputs::input_size> input_type;
	typedef arma::vec::fixed<mids::intermediate_size> intermediate_type;
	typedef arma::mat::fixed<config::buffer_headers,config::buffer_size> buffer_type;

	typedef double value_type;
	typedef double time_type;

public:

	static void rhs(
		const state_type 			&x,
		state_type 					&x_dot,
		const time_type				&t,
		const intermediate_type 	&last_observed_mids,
		const time_type 			&last_observed_t,
		input_type					&u
		);

	static void observer(
		const state_type 			&x ,
		const double 				&t,
		observer_type 				&ymat,
		const intermediate_type 	&last_observed_mids,
		const time_type 			&last_observed_t,
		input_type					&u
		);

	static void intermediates(
		const input_type			&u,
		const state_type			&x,
		intermediate_type			&mid,
		const time_type				&t,
		const intermediate_type		&last_observed_mids,
		const time_type				&last_observed_t
		);

	static double input(const time_type t,input_type &u)
	{
		_unused(t);
		_unused(u);

		double next_sudden_change_time=-1;
		return next_sudden_change_time;
	}

protected:

};

#include "autogenerated/model_observer.hpp"
#include "model_mids.hpp"
#include "model_rhs.hpp"
