#pragma once

#include "types.hpp"
#include "constants.hpp"

using namespace arma;

class Model
{
public:

	static void rhs(
		const state_type 			&x,
		state_type 					&x_dot,
		const time_type				&t,
		const state_type 			&last_observed_x,
		const time_type 			&last_observed_t,
		input_type					&u
		);

	static void observer(
		const state_type 			&x ,
		const double 				&t,
		observer_type 				&ymat,
		const state_type 			&last_observed_x,
		const time_type 			&last_observed_t,
		input_type					&u
		);

	static void intermediates(
		const input_type &u,
		const state_type &x,
		intermediate_type &mid,
		const time_type &t,
		const state_type &last_observed_x,
		const time_type &last_observed_t
		);

	static double input(const time_type t,input_type &u)
	{
		_unused(t);
		_unused(u);

		double next_sudden_change_time=-1;
		return next_sudden_change_time;
	}

protected:

};

#include "autogenerated/model_observer.hpp"
#include "model_mids.hpp"
#include "model_rhs.hpp"
