
// *** Warning:
// *** auto-generated file and subjected to be overwritten

// path: ./app_models/empty_model/autogenerated/model_inputs.hpp

#pragma once

namespace inputs
{


	// total size of inputs vector
	const int input_size=0;
}
