
// *** Warning:
// *** auto-generated file and subjected to be overwritten

// path: ./app_models/empty_model/autogenerated/model_intermediates.hpp

#pragma once

namespace mids
{


	// total size of intermediate vector
	const int intermediate_size=0;
}
