
// *** Warning:
// *** auto-generated file and subjected to be overwritten

// path: ./app_models/empty_model/autogenerated/model_observer.hpp

#pragma once

void Model::observer(
	const state_type 			&x ,
	const double 				&t,
	observer_type 				&ymat,
	const intermediate_type 	&last_observed_mids,
	const time_type 			&last_observed_t,
	input_type					&u
	)
{
	intermediate_type mid;
	intermediates(u,x,mid,t,last_observed_mids,last_observed_t);

	

	_unused(ymat);

}
