
// *** Warning:
// *** auto-generated file and subjected to be overwritten

// path: ./app_models/empty_model/autogenerated/model_outputs.hpp

#pragma once

namespace outputs
{
	const std::string output_header[]={
		
	};

	

	

	// total size of outputs vector
	const int output_size=0;
	
	//Export list
	struct FigureList
	{
		std::string file_suffix; // no space is accepted in file suffix name
		int output_index;
	} figure_list[]={
		
	};
}
