
// *** Warning:
// *** auto-generated file and subjected to be overwritten

// path: ./app_models/empty_model/autogenerated/model_states.hpp

#pragma once

namespace states
{
	

	

	// total size of states vector
	const int state_size=0;
}
