
// *** Warning:
// *** auto-generated file and subjected to be overwritten

// path: ./app_models/empty_model/autogenerated/user_template.hpp

// inputs

	

	

// intermediates

	

	

// states

	

	
