#pragma once
#include <armadillo>
#include "autogenerated/model_outputs.hpp"
#include "autogenerated/model_states.hpp"
#include "autogenerated/model_inputs.hpp"
#include "autogenerated/model_intermediates.hpp"
#include "../../application/config.hpp"
