
// *** Warning:
// *** auto-generated file and subjected to be overwritten

// path: ./app_models/classical_washoutfilter/autogenerated/model_inputs.hpp

#pragma once

namespace inputs
{
	// u[0]	surge_acc
	// u[1]	pitch_angle

	const uint surge_acc=0;
	const uint pitch_angle=1;

	// total size of inputs vector
	const int input_size=2;
}
