
// *** Warning:
// *** auto-generated file and subjected to be overwritten

// path: ./app_models/classical_washoutfilter/autogenerated/model_states.hpp

#pragma once

namespace states
{
	// x0	surge_hp_x1
	// x1	surge_hp_x2
	// x2	surge_kin_vel
	// x3	surge_kin_pos
	// x4	surge_lp_x1
	// x5	surge_lp_x2
	// x6	pitch_hp_x1

	const int surge_hp_x1=0;
	const int surge_hp_x2=1;
	const int surge_kin_vel=2;
	const int surge_kin_pos=3;
	const int surge_lp_x1=4;
	const int surge_lp_x2=5;
	const int pitch_hp_x1=6;

	// total size of states vector
	const int state_size=7;
}
