
// *** Warning:
// *** auto-generated file and subjected to be overwritten

// path: ./app_models/classical_washoutfilter/autogenerated/model_intermediates.hpp

#pragma once

namespace mids
{
	// m0	surge_input_acc_ref
	// m1	surge_hp_out
	// m2	surge_kin_acc
	// m3	surge_kin_vel
	// m4	surge_kin_pos
	// m5	surge_lp_out
	// m6	tilt_coordination
	// m7	pitch_input_angle_ref
	// m8	pitch_hp_out
	// m9	pitch_angle
	// m10	tilt_force
	// m11	specific_force

	const int surge_input_acc_ref=0;
	const int surge_hp_out=1;
	const int surge_kin_acc=2;
	const int surge_kin_vel=3;
	const int surge_kin_pos=4;
	const int surge_lp_out=5;
	const int tilt_coordination=6;
	const int pitch_input_angle_ref=7;
	const int pitch_hp_out=8;
	const int pitch_angle=9;
	const int tilt_force=10;
	const int specific_force=11;

	// total size of mids vector
	const int intermediate_size=12;
}
