
// *** Warning:
// *** auto-generated file and subjected to be overwritten

// path: ./app_models/classical_washoutfilter/autogenerated/model_outputs.hpp

#pragma once

namespace outputs
{
	const std::string output_header[]={
		"surge_input_acc_ref",
		"surge_hp_out",
		"surge_kin_acc",
		"surge_kin_vel",
		"surge_kin_pos",
		"surge_lp_out",
		"specific_force",
	};

	// o0	surge_input_acc_ref
	// o1	surge_hp_out
	// o2	surge_kin_acc
	// o3	surge_kin_vel
	// o4	surge_kin_pos
	// o5	surge_lp_out
	// o6	specific_force

	const int surge_input_acc_ref=0;
	const int surge_hp_out=1;
	const int surge_kin_acc=2;
	const int surge_kin_vel=3;
	const int surge_kin_pos=4;
	const int surge_lp_out=5;
	const int specific_force=6;

	// total size of output vector
	const int output_size=7;

	//Export list
	struct ExpList
	{
		std::string file_suffix; // no space is accepted in file suffix name
		int output_index;
	} figure_list[]={
		{"surge_input_acc_ref",outputs::surge_input_acc_ref},
		{"specific_force",outputs::specific_force},
	};
}
