
// *** Warning:
// *** auto-generated file and subjected to be overwritten

// path: ./app_models/classical_washoutfilter/autogenerated/model_intermediates.hpp

#pragma once

namespace mids
{
	// m[0]	surge_input_acc_ref
	// m[1]	surge_hp_out
	// m[2]	surge_kin_acc
	// m[3]	surge_kin_vel
	// m[4]	surge_kin_pos
	// m[5]	surge_lp_out
	// m[6]	tilt_coordination
	// m[7]	pitch_input_angle_ref
	// m[8]	pitch_hp_out
	// m[9]	pitch_angle
	// m[10]	tilt_force
	// m[11]	specific_force

	const uint surge_input_acc_ref=0;
	const uint surge_hp_out=1;
	const uint surge_kin_acc=2;
	const uint surge_kin_vel=3;
	const uint surge_kin_pos=4;
	const uint surge_lp_out=5;
	const uint tilt_coordination=6;
	const uint pitch_input_angle_ref=7;
	const uint pitch_hp_out=8;
	const uint pitch_angle=9;
	const uint tilt_force=10;
	const uint specific_force=11;

	// total size of mids vector
	const int intermediate_size=12;
}
