
// *** Warning:
// *** auto-generated file and subjected to be overwritten

// path: ./app_models/classical_washoutfilter/autogenerated/model_outputs.hpp

#pragma once

namespace outputs
{
	const std::string output_header[]={
		"surge_input_acc_ref",
		"surge_hp_out",
		"surge_kin_acc",
		"surge_kin_vel",
		"surge_kin_pos",
		"surge_lp_out",
		"specific_force"
	};

	// y0	surge_input_acc_ref;
	// y1	surge_hp_out;
	// y2	surge_kin_acc;
	// y3	surge_kin_vel;
	// y4	surge_kin_pos;
	// y5	surge_lp_out;
	// y6	specific_force;

	const uint surge_input_acc_ref=0;
	const uint surge_hp_out=1;
	const uint surge_kin_acc=2;
	const uint surge_kin_vel=3;
	const uint surge_kin_pos=4;
	const uint surge_lp_out=5;
	const uint specific_force=6;

	// total size of outputs vector
	const int output_size=7;
	
	//Export list
	struct FigureList
	{
		std::string file_suffix; // no space is accepted in file suffix name
		int output_index;
	} figure_list[]={
		{"surge_input_acc_ref",outputs::surge_input_acc_ref},
		{"specific_force",outputs::specific_force}
	};
}
