
// *** Warning:
// *** auto-generated file and subjected to be overwritten

// path: ./app_models/puma_560_robot/autogenerated/model_outputs.hpp

#pragma once

namespace outputs
{
	const std::string output_header[]={
		"theta_desired[0]",
		"theta_desired[1]",
		"theta_desired[2]",
		"theta[0]",
		"theta[1]",
		"theta[2]",
		"position[0]",
		"position[1]",
		"position[2]",
		"error"
	};

	// y0	theta_desired[0];
	// y1	theta_desired[1];
	// y2	theta_desired[2];
	// y3	theta[0];
	// y4	theta[1];
	// y5	theta[2];
	// y6	position[0];
	// y7	position[1];
	// y8	position[2];
	// y9	error;

	const uint theta_desired_0=0;
	const uint theta_desired_1=1;
	const uint theta_desired_2=2;
	const uint theta_0=3;
	const uint theta_1=4;
	const uint theta_2=5;
	const uint position_0=6;
	const uint position_1=7;
	const uint position_2=8;
	const uint error=9;

	// total size of outputs vector
	const int output_size=10;
	
	//Export list
	struct FigureList
	{
		std::string file_suffix; // no space is accepted in file suffix name
		int output_index;
	} figure_list[]={
		{"theta_desired[0]",outputs::theta_desired_0},
		{"theta_desired[1]",outputs::theta_desired_1},
		{"theta_desired[2]",outputs::theta_desired_2},
		{"theta[0]",outputs::theta_0},
		{"theta[1]",outputs::theta_1},
		{"theta[2]",outputs::theta_2},
		{"position[0]",outputs::position_0},
		{"position[1]",outputs::position_1},
		{"position[2]",outputs::position_2},
		{"error",outputs::error}
	};
}
