
// *** Warning:
// *** auto-generated file and subjected to be overwritten

// path: ./app_models/puma_560_robot/autogenerated/model_states.hpp

#pragma once

namespace states
{
	// x[0:2]	theta_vel[3]
	// x[3:5]	theta_pos[3]

	const uint theta_vel_0=0;
	const uint theta_vel_end=2;
	const uint theta_pos_0=3;
	const uint theta_pos_end=5;

	// total size of states vector
	const int state_size=6;
}
