
// *** Warning:
// *** auto-generated file and subjected to be overwritten

// path: ./app_models/puma_560_robot/autogenerated/model_inputs.hpp

#pragma once

namespace inputs
{
	// u[0:2]	theta_acc_ref[3]

	const uint theta_acc_ref_0=0;
	const uint theta_acc_ref_1=1;
	const uint theta_acc_ref_2=2;
	const uint theta_acc_ref_end=2;

	// total size of inputs vector
	const int input_size=3;
}
