#!/bin/bash

me=`basename $0`
out_folder=./application/autogenerated
out_file=$out_folder/embed_models.hpp
model_file=./models
models_folder_name=app_models

if [ ! -d $out_folder ]
then
	mkdir -p $out_folder
fi

echo "">$out_file
./scripts/autogen_code_header.sh  >>$out_file
echo "// path: $out_file">>$out_file
echo "">>$out_file

#includes
echo "">>$out_file
echo "// include models">>$out_file
echo "">>$out_file
vector_input=($(./scripts/read_column.sh 0 $model_file))
for index in ${!vector_input[*]}
do
	echo -e "#include \"../../$models_folder_name/${vector_input[index]//\"/}/model.hpp\"">>$out_file
done
echo "">>$out_file

echo "$out_file updated"
