#!/bin/bash

# this script calls the other script to generate automatic codes.

# list of scripts

me=`basename $0`
if [ ! "$1" ]
then
	echo "no model argument is received ($me)"
	exit 1
fi

model_name=$1
model_folder="./app_models/$model_name"
list_folder=$model_folder/vectors
autogen_folder=$model_folder/autogenerated
list_suffix=list


#folder
if [ ! -d $autogen_folder ]
then
	mkdir -p $autogen_folder
	echo "directory created: $autogen_folder"
fi

#functions
input()
{
	echo $list_folder/$1.$list_suffix
}

output()
{
	echo $autogen_folder/model_$1.hpp
}

script()
{
	echo ./scripts/model_$1.sh
}

#user template
./scripts/user_template.sh $model_name $model_folder

#output
$(script "outputs") $(input "outputs") $(output "outputs")

#observer
$(script "observer") $(input "outputs") $(output "observer")

#states
$(script "states") $(input "states") $(output "states")

#intermediates
$(script "intermediates") $(input "intermediates") $(output "intermediates")

#inputs
$(script "inputs") $(input "inputs") $(output "inputs")
