#!/bin/bash

me=`basename $0`
model_name=$1
model_folder=$2

in_folder=$model_folder/vectors
input_u=$in_folder/inputs.list
input_mids=$in_folder/intermediates.list
input_x=$in_folder/states.list

out_file=$model_folder/autogenerated/user_template.hpp

if [ ! "$1" ]
then
	echo "no model folder is received ($me)"
	exit 1
fi

if [ ! -d $model_folder ]
then
	echo "error: model folder $model not found. ($me)"
	exit 1234	
fi

echo "">$out_file
./scripts/autogen_code_header.sh  >>$out_file
echo "// path: $out_file">>$out_file
echo "">>$out_file

#inputs
echo "">>$out_file
echo "// inputs">>$out_file
echo "">>$out_file
vector_input=($(./scripts/read_column.sh 0 $input_u))
for index in ${!vector_input[*]}
do
	echo -e "\t// u$index\t${vector_input[index]//\"/}">>$out_file
done
echo "">>$out_file
for index in ${!vector_input[*]}
do
	echo -e "\tu(inputs::${vector_input[index]//\"/})=...">>$out_file
done
echo "">>$out_file

#intermediates
echo "">>$out_file
echo "// intermediates">>$out_file
vector_mids=($(./scripts/read_column.sh 0 $input_mids))
echo "">>$out_file
for index in ${!vector_mids[*]}
do
	echo -e "\t// m$index\t${vector_mids[index]//\"/}">>$out_file
done
echo "">>$out_file
for index in ${!vector_mids[*]}
do
	echo -e "\tmid(mids::${vector_mids[index]//\"/})=...">>$out_file
done
echo "">>$out_file

#states
echo "">>$out_file
echo "// states">>$out_file
echo "">>$out_file
vector_x=($(./scripts/read_column.sh 0 $input_x))
for index in ${!vector_x[*]}
do
	echo -e "\t// x$index\t${vector_x[index]//\"/}">>$out_file
done
echo "">>$out_file
for index in ${!vector_x[*]}
do
	echo -e "\tx_dot(states::${vector_x[index]//\"/})=...">>$out_file
done
echo "">>$out_file
