
// *** Warning:
// *** auto-generated file and subjected to be overwritten

// path: ./application/autogenerated/embed_models.hpp

#pragma once

// include models

#include "../../app_models/puma_560_robot/model.hpp"
