
// *** Warning:
// *** auto-generated file and subjected to be overwritten

// path: ./application/autogenerated/embed_models.hpp

#pragma once

// include models

#include "../../app_models/classical_washoutfilter/model.hpp"
