
// *** Warning:
// *** auto-generated file and subjected to be overwritten

// path: ./app_models/transmission_line/autogenerated/model_inputs.hpp

#pragma once

namespace inputs
{
	// u[0]	v_in

	const uint v_in=0;

	// total size of inputs vector
	const int input_size=1;
}
