
// *** Warning:
// *** auto-generated file and subjected to be overwritten

// path: ./app_models/transmission_line/autogenerated/model_states.hpp

#pragma once

namespace states
{
	// x[0:99]	q[100]
	// x[100:199]	phi[100]

	const uint q_0=0;
	const uint q_end=99;
	const uint phi_0=100;
	const uint phi_end=199;

	// total size of states vector
	const int state_size=200;
}
