
// *** Warning:
// *** auto-generated file and subjected to be overwritten

// path: ./app_models/transmission_line/autogenerated/model_intermediates.hpp

#pragma once

namespace mids
{
	// m[0]	v_in
	// m[1]	v_end

	const uint v_in=0;
	const uint v_end=1;

	// total size of mids vector
	const int intermediate_size=2;
}
