
// *** Warning:
// *** auto-generated file and subjected to be overwritten

// path: ./app_models/transmission_line/autogenerated/model_outputs.hpp

#pragma once

namespace outputs
{
	const std::string output_header[]={
		"v_in",
		"v_end"
	};

	// y0	v_in;
	// y1	v_end;

	const uint v_in=0;
	const uint v_end=1;

	// total size of outputs vector
	const int output_size=2;
	
	//Export list
	struct FigureList
	{
		std::string file_suffix; // no space is accepted in file suffix name
		int output_index;
	} figure_list[]={
		{"v_in",outputs::v_in},
		{"v_end",outputs::v_end}
	};
}
